# Change these first
owner: fuww # Your GitHub organization or username, where this repository lives
repo: status.fashionunited.com # The name of this repository

sites:
  - name: fashionunited.at
    url: https://fashionunited.at
  - name: fashionunited.be
    url: https://fashionunited.be
  - name: fashionunited.ca
    url: https://fashionunited.ca
  - name: fashionunited.ch
    url: https://fashionunited.ch
  - name: fashionunited.cl
    url: https://fashionunited.cl
  - name: fashionunited.cn
    url: https://fashionunited.cn
  - name: fashionunited.co
    url: https://fashionunited.co
  - name: fashionunited.co.nz
    url: https://fashionunited.co.nz
  - name: fashionunited.co.uk
    url: https://fashionunited.co.uk
  - name: fashionunited.com
    url: https://fashionunited.com
  - name: fashionunited.com.ar
    url: https://fashionunited.com.ar
  - name: fashionunited.com.br
    url: https://fashionunited.com.br
  - name: fashionunited.com.pe
    url: https://fashionunited.com.pe
  - name: fashionunited.com.tr
    url: https://fashionunited.com.tr
  - name: fashionunited.cz
    url: https://fashionunited.cz
  - name: fashionunited.de
    url: https://fashionunited.de
  - name: fashionunited.dk
    url: https://fashionunited.dk
  - name: fashionunited.es
    url: https://fashionunited.es
  - name: fashionunited.fi
    url: https://fashionunited.fi
  - name: fashionunited.fr
    url: https://fashionunited.fr
  - name: fashionunited.hk
    url: https://fashionunited.hk
  - name: fashionunited.hu
    url: https://fashionunited.hu
  - name: fashionunited.ie
    url: https://fashionunited.ie
  - name: fashionunited.in
    url: https://fashionUnited.in
  - name: fashionunited.info
    url: https://fashionunited.info
  - name: fashionunited.it
    url: https://fashionunited.it
  - name: fashionunited.jp
    url: https://fashionunited.jp
  - name: fashionunited.lu
    url: https://fashionunited.lu
  - name: fashionunited.mx
    url: https://fashionunited.mx
  - name: fashionunited.nl
    url: https://fashionunited.nl
  - name: fashionunited.no
    url: https://fashionunited.no
  - name: fashionunited.nz
    url: https://fashionunited.nz
  - name: fashionunited.pl
    url: https://fashionunited.pl
  - name: fashionunited.pt
    url: https://fashionunited.pt
  - name: fashionunited.ru
    url: https://fashionunited.ru
  - name: fashionunited.se
    url: https://fashionunited.se
  - name: fashionunited.tv
    url: https://fashionunited.tv
  - name: fashionunited.uk
    url: https://fashionunited.uk
  - name: fashionweekweb.com
    url: https://fashionweekweb.com
  - name: internationalfashionjobs.com
    url: https://internationalfashionjobs.com
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fashionunited.com
  # baseUrl: /your-repo-name
  logoUrl: https://imagedelivery.net/7czaBv4WuiSsJFxi583jUw/4054f10b-e32a-4753-b280-499cf7a53b00/public
  name: FashionUnited
  introTitle: "**FashionUnited** uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the status page which uses **real-time** data from our [GitHub repository](https://github.com/fuww/status.fashionunited.com).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
